#import "template.typ": *

#show: project

#index()
= Contest
#insert("template.h")
#insert(".bashrc")
#insert(".vimrc")
#insert("troubleshoot.txt")
#insert("binary_search.h")
= Data Structures
#insert("ds/hashmap.h")
#insert("ds/order_statistic_tree.h")
// #insert("ds/uf.h")
#insert("ds/uf_rollback.h")
#insert("ds/convex_hull_trick.h")
#insert("ds/compress_coords.h")
#insert("ds/sparse_table.h")
#insert("ds/st/iterative_segment_tree.h")
#insert("ds/fenwick_tree.h")
#insert("ds/compressed_fenwick_tree_2d.h")
#insert("ds/st/split.h")
#insert("ds/st/recursive_segment_tree.h")
#insert("ds/st/persistent_segment_tree.h")
#insert("ds/st/tag.h")
#insert("ds/st/lazy_segment_tree.h")
#insert("ds/st/persistent_lazy_segment_tree.h")
#insert("ds/treap_node.h")
#insert("ds/treap.h")
#insert("ds/mo.h")
#insert("ds/bit_vector.h")
#insert("ds/wavelet_matrix.h")
#insert("ds/lichao_lazy.h")
= Number Theory
// #insert("nt/mod_pow.h")
#insert("nt/modmul_ll.h")
#insert("nt/miller_rabin.h")
#insert("nt/factor.h")
#insert("nt/mod_arithmetic.h")
#insert("nt/euclid.h")
#insert("nt/morbius.h")
#insert("nt/crt.h")
#insert("nt/continued_fractions.h")
// #insert("nt/eratosthenes.h")
#insert("nt/fast_eratosthenes.h")
#insert("nt/frac_binary_search.h")
#insert("nt/mod_log.h")
#insert("nt/mod_sqrt.h")
#insert("nt/mod_sum.h")
#insert("nt/phi_function.h")
= Numerical
#insert("numerical/berlekamp_massey.h")
#insert("numerical/polynomial.h")
#insert("numerical/poly_interpolate.h")
#insert("numerical/poly_roots.h")
#insert("numerical/linear_recurrence.h")
#insert("numerical/int_determinant.h")
#insert("numerical/tridiagonal.h")
#insert("numerical/matrix_inv_mod.h")
#insert("numerical/solve_linear.h")
#insert("numerical/fst.h")
#insert("numerical/ntt.h")
#insert("numerical/golden_section_search.h")
#insert("numerical/hill_climbing.h")
#insert("numerical/integrate.h")
#insert("numerical/integrate_adaptive.h")
#insert("numerical/simplex.h")
= Geometry
#insert("geometry/point.h")
#insert("geometry/line_distance.h")
#insert("geometry/segment_distance.h")
#insert("geometry/line_intersection.h")
#insert("geometry/on_segment.h")
#insert("geometry/segment_intersection.h")
#insert("geometry/side_of.h")
#insert("geometry/linear_transformation.h")
#insert("geometry/closest_pair.h")
#insert("geometry/convex_hull.h")
#insert("geometry/manhattan_mst.h")
#insert("geometry/circumcircle.h")
#insert("geometry/minimum_enclosing_circle.h")
#insert("geometry/minkowski.h")
#insert("geometry/halfplane_intersection.h")
#insert("geometry/fast_delaunay.h")
#insert("geometry/polygon_area.h")
#insert("geometry/inside_polygon.h")
#insert("geometry/polygon_cut.h")
#insert("geometry/polygon_center.h")
#insert("geometry/polygon_union.h")
#insert("geometry/line_hull_intersection.h")
#insert("geometry/circle_polygon_intersection.h")
= 3D Geometry
#insert("geometry/point_3d.h")
#insert("geometry/hull_3d.h")
#insert("geometry/polyhedron_volume.h")
#insert("geometry/spherical_distance.h")
#insert("geometry/spherical_segment_intersection.txt")
= Strings
#insert("strings/hashing.h")
#insert("strings/trie.h")
#insert("strings/suffix_array.h")
#insert("strings/suffix_tree.h")
#insert("strings/suffix_automaton.h")
#insert("strings/kmp.h")
#insert("strings/zfunc.h")
#insert("strings/manacher.h")
#insert("strings/aho_corasick.h")
= Graphs
// #insert("graph/bellman_ford.h")
#insert("graph/johnson.txt")
#insert("graph/topo_sort.h")
#insert("graph/scc.h")
#insert("graph/bridges.h")
#insert("graph/cuts.h")
#insert("graph/2sat.h")
#insert("graph/lca.h")
#insert("graph/binary_lifting.h")
#insert("graph/hld.h")
#insert("graph/lct.h")
#insert("graph/centroid_tree.h")
#insert("graph/euler_walk.h")
#insert("graph/maximum_clique.h")
#insert("graph/edge_coloring.h")
#insert("graph/directed_mst.h")
#insert("graph/dominator_tree.h")
#insert("graph/matroid_intersection.h")
= Flow
#insert("flow/hopcroft_karp.h")
#insert("flow/dinic.h")
#insert("flow/push_relabel.h")
#insert("flow/maxflow_with_demands.h")
#insert("flow/mcmf.h")
#insert("flow/weighted_matching.h")
// #insert("flow/general_matching.h")
#insert("flow/blossom.h")
= Various
#insert("various/ternary_search.h")
#insert("various/interval_container.h")
#insert("various/constant_intervals.h")
#insert("various/interval_cover.h")
// #insert("various/lis.h")
#insert("various/fast_knapsack.h")
#insert("various/divide_and_conquer_dp.h")
#insert("various/knuth_dp.h")
#insert("various/combinatorial.h")
#insert("various/nt.h")
#insert("various/random.h")
