/* -
name = "Number Theory"
type = "typst"
[info]
- */
== Pythagorean Triples
The Pythagorean triples are uniquely generated by
$ a=k dot (m^2-n^2), quad b=k dot (2m n), quad c=k dot (m^2+n^2), $
with $m > n > 0$, $k > 0$, $m perp n$, and either $m$ or $n$ even.

== Primes
$p=962592769$ is such that $2^21 divides p-1$, which may be useful. For hashing
use 970592641 (31-bit number), 31443539979727 (45-bit), 3006703054056749
(52-bit). There are 78498 primes less than $1 thin 000 thin 000$.

Primitive roots exist modulo any prime power $p^a$, except for $p = 2, a > 2$, and there are $phi.alt(phi.alt(p^a))$ many.
For $p = 2, a > 2$, the group $ZZ_(2^a)^times$ is instead isomorphic to $ZZ_2 times ZZ_(2^(a-2))$.

== Estimates
$sum_(d divides n) d = O(n log log n)$.

The number of divisors of $n$ is at most around 100 for $n < 5"e"4$, 500 for $n < 1"e"7$, 2000 for $n < 1"e"10$, 200000 for $n < 1"e"19$.

== Mobius Function
$ mu(n) = cases(
  0 quad& n "is not square free",
  1 quad& n "has even number of prime factors",
  -1 quad& n "has odd number of prime factors",
) $
Mobius Inversion:
$ g(n) = sum_(d divides n) f(d) arrow.l.r.double f(n) = sum_(d divides n) mu(d)g(n\/d) $
Other useful formulas/forms:

$sum_(d divides n) mu(d) = [n = 1]$ (very useful)

$g(n) = sum_(n divides d) f(d) arrow.l.r.double f(n) = sum_(n divides d) mu(d\/n)g(d)$

$g(n) = sum_(1 <= m <= n) f(floor(n/m)) arrow.l.r.double f(n) = sum_(1 <= m <= n) mu(m)g(floor(n/m))$
